version: '3.8'
services:
  apisix:
    image: apache/apisix:3.11.0-debian
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    depends_on:
      - etcd
    networks:
      - apisix-network
    ports:
      - "9080:9080"  # Exponer puerto 9080 en el host
      - "9180:9180"  # Exponer puerto 9180 en el host

  etcd:
    image: bitnami/etcd:3.5.11
    container_name: etcd
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"  # Exponer puerto 2379 en el host
    networks:
      - apisix-network

  nats:
    image: nats:latest
    container_name: nats
    networks:
      - apisix-network
    ports:
      - "4222:4222"  # Exponer puerto 4222 en el host
      - "8222:8222"  # Exponer puerto 8222 en el host

  api-server:
    build:
      context: ./api-server  # Indica el directorio donde está el Dockerfile
      dockerfile: Dockerfile  # Puedes omitir esta línea si el archivo se llama exactamente 'Dockerfile'
    container_name: api-server
    environment:
      - NATS_URL=nats://nats:4222
    networks:
      - apisix-network
    ports:
      - "3000:3000"  # Exponer puerto 3000 en el host
    depends_on:
      - nats
      
networks:
  apisix-network:
    driver: bridge  # Usar una red personalizada tipo 'bridge'

volumes:
  etcd_data:
    #driver: local
  nats-data:
    #driver: local
