apisix:
  # Cambiar `node_listen` para que escuche en todas las interfaces
  node_listen: 9080
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"  # Asegúrate de que el control también esté escuchando en todas las interfaces
    port: 9092

deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0  # Permite el acceso desde cualquier IP (solo para desarrollo, ajusta en producción)

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  # Configuración de ETCD para asegurar que se conecta correctamente
  etcd:
    host:
      - "http://etcd:2379"  # Asumiendo que el contenedor de ETCD se llama 'etcd'
    prefix: "/apisix"
    timeout: 30

# Rutas de APISIX para redirigir las peticiones a los servicios de 'api-server'
routes:
  # Ruta para registrar usuarios
  - uri: /auth/register
    methods: ["POST"]
    upstream:
      type: round-robin
      nodes:
        "api-server:3000": 1  # Nombre de contenedor 'api-server' para la red de Docker

  # Ruta para iniciar sesión
  - uri: /auth/login
    methods: ["POST"]
    upstream:
      type: round-robin
      nodes:
        "api-server:3000": 1

  # Ruta para trabajar con funciones
  - uri: /functions/*
    methods: ["POST"]
    upstream:
      type: round-robin
      nodes:
        "api-server:3000": 1

  # Ruta para ejecutar funciones específicas
  - uri: /functions/*/execute
    methods: ["POST"]
    upstream:
      type: round-robin
      nodes:
        "api-server:3000": 1

  # Ruta para eliminar funciones
  - uri: /functions/*/delete
    methods: ["DELETE"]
    upstream:
      type: round-robin
      nodes:
        "api-server:3000": 1
